### ISSUE TITLE
Övergripande

### ISSUE THREAD

**Issue by JuliaSivartsson** [AndreasBom/1dv450_ab22cw#1]
INSTALLATION
- Väldigt tydliga instruktioner om hur man får igång applikationen, jag valde att installera den via Cloud9. Följde instruktionerna till punkt och pricka och det gick helt smärtfritt att få igång applikationen.
- Nu var det inget krav på att få upp applikationen online vad jag vet men det kanske hade varit lärorikt att ha genomfört det steget också (även ifall installation hade krånglat så man i alla fall kunde se en fungerande version av applikationen).

VISUELLT
- Snyggt att applikationen hämtar profilbild från gravatar!
- Plus för att man blir inloggad vid registrering (det var inget jag själv han lösa under laboration1 men hade det i tankarna att det är en bra feature).
- Jag är själv lite osäker på hur det här med Api-nycklar fungerar men borde jag få ut en nyckel innan applikationen är registrerad? Borde den kanske inte genereras efter jag tryckt på "Lägg till"? 
- Väldigt tydligt gränssnitt så det är väldigt lätt att klicka sig runt och hitta saker och ting väldigt fort.
- Gillar även att man får upp en confirmation vid radering av applikation!

KOD
- Gillar att du använt partiella vyer för t.ex. formulären. Även om vyerna är väldigt clean som de är så skapar det en bättre överblick.
- Metoder och klasser har väldigt självförklarande namn jag tycker att mängden kommentarer du använder är okej, även om det för någon som absolut aldrig tittat på ruby tidigare kanske skulle velat ha några till, men nu petar jag lite på småsaker. Kanske t.ex. vad before_action överst i controllers har för uppgift.
- Jag har precis satt mig in i ruby så jag är lite osäker på vad för hjälpfunktioner som finns och så vidare, men vad jag kan se har du använt dig av flera. T.ex. att has_secure_password används för användare och då även authenticate.
- Jag tycker att du har fått till dina routes väldigt tydligt och bra. Kanske kunde överbliven, bortkommenterad kod tas bort (default koden) men du kanske får användning av den senare och därför sparat den.
- Väldigt snyggt att du gjort så att man kan välja att hämta information som json också.

**Comment by 1dv450** [comment]
:+1:

**Comment by AndreasBom** [comment]
:+1:  :)
