### ISSUE TITLE
Kommer åt alla applikationer

### ISSUE THREAD

**Issue by JuliaSivartsson** [AndreasBom/1dv450_ab22cw#3]
- Tror att jag hittat en säkerhetsbrist i applikationen. Jag var inloggad som användare med id 5, men gick via url:en till "/users/4" och fick då upp användaren jag skapade tidigare (jag kan göra så på alla användare). Detta gav mig åtkomst till profilen för användaren med id 4. Där kan jag välja att radera den användarens applikationer, vilket inte är så bra då man vill hålla den funktionaliteten tillgänglig enbart för korrekt användare och admin.

Det borde gå att lösa med någon liknande if-sats runt "ta bort"-knappen:
<% if current_user.email == @user.email || is_admin?(current_user) %>

**Comment by 1dv450** [comment]
Bra! När issues är fixade kan du stänga dem

**Comment by AndreasBom** [comment]
Fixad
